name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0 # Required for full git history
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.410
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Setup Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    
    - name: Build
      run: dotnet build --no-restore
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal